version: "3.8" 
services:
  mongo:   
    image: mongo 
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=pl-health-service
    volumes: 
      - ./mongo-volume:/data/db 
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo